cars=['bmw','audi','toyota','subaru']
print("Here is the original list:")
print(cars)
cars.sort()
print(cars)
cars.sort(reverse=True)
print(cars)
cars=["bmw","audi","toyota","subaru"]
print("\nHere is the sorted list:")
print(sorted(cars))
print("\nHere is the original list again:")
print(cars)
sorted_cars_desc=sorted(cars,reverse=True)
print(sorted_cars_desc)
print(cars)